#!/bin/bash

git clone git@github.com:nomensa/FormBuilder-Laravel.git temp_git_repo

mv temp_git_repo/.git .git

rm -rf temp_git_repo

echo "Enter your GitHub user email address: "
read email

git config user.email $email
